package p1verify

import (
	"crypto/ed25519"
	"crypto/sha256"
	"errors"
	"fmt"
	"reflect"
)

func sign1(raw []byte)(protected []byte,unprotected map[any]any,payload any,signature []byte,err error){v,e:=decodeCBOR(raw);if e!=nil{err=e;return};tag,ok:=v.(cborTag);if !ok||tag.Number!=18{err=errors.New("expected tagged COSE_Sign1");return};a,ok:=tag.Value.([]any);if !ok||len(a)!=4{err=errors.New("invalid COSE_Sign1 array");return};protected,ok=a[0].([]byte);if !ok{err=errors.New("protected header must be bstr");return};unprotected,ok=a[1].(map[any]any);if !ok{err=errors.New("unprotected header must be map");return};payload=a[2];signature,ok=a[3].([]byte);if !ok||len(signature)!=64{err=errors.New("signature must be 64-byte bstr")};return}
func sigStructure(protected,payload []byte)[]byte{b,_:=encodeCBOR([]any{"Signature1",protected,[]byte{},payload});return b}
func expectedMapEqual(a,b map[any]any)bool{return reflect.DeepEqual(a,b)}
func leafHash(entry []byte)[]byte{h:=sha256.Sum256(append([]byte{0},entry...));return h[:]}

func verifyP1A3(raw,bundleRaw []byte,issuer ed25519.PublicKey,issuerDER []byte,ts ed25519.PublicKey,tsDER []byte)error{
	v,e:=strictJSON(raw);if e!=nil{return e};c:=obj(v);if str(c["standard"])!="EIGIIB-P1-A3-1.0"||str(c["profile"])!="scitt-p1-a2-receipt-v1"||str(c["trust_scope"])!="supplied-public-keys-only"{return errors.New("P1-A3 constants mismatch")};binding:=obj(c["binding"]);if !eqID(binding["p1A2Bundle"],ident(bundleRaw))||str(binding["vds"])!="RFC9162_SHA256"||integer(binding["vdsId"])!=1||str(binding["proofType"])!="inclusion"{return errors.New("P1-A3 binding mismatch")}
	signed:=obj(c["signedStatement"]);sraw,e:=b64(str(signed["data"]));if e!=nil{return e};if !eqID(signed["identity"],ident(sraw))||!eqID(signed["issuerKeySpki"],ident(issuerDER)){return errors.New("Signed Statement identity mismatch")};p,up,payloadAny,sig,e:=sign1(sraw);if e!=nil{return e};if len(up)!=0{return errors.New("Signed Statement unprotected header must be empty")};payload,ok:=payloadAny.([]byte);if !ok{return errors.New("Signed Statement payload must be bstr")};pmAny,e:=decodeCBOR(p);if e!=nil{return e};pm:=pmAny.(map[any]any);subject:="urn:eigiib:p1-a2:"+ident(bundleRaw).Digest;expected:=map[any]any{int64(1):int64(-8),int64(3):"application/cbor",int64(4):sha256Bytes(issuerDER),int64(15):map[any]any{int64(1):"https://eigiib.example/p1-a3/issuer",int64(2):subject},int64(16):"application/scitt-statement+cose"};if !expectedMapEqual(pm,expected){return fmt.Errorf("Signed Statement protected header mismatch: %#v",pm)};dpAny,e:=decodeCBOR(payload);if e!=nil{return e};dp:=dpAny.(map[any]any);expectedDP:=map[any]any{"mediaType":"application/vnd.dev.sigstore.bundle.v0.3+json","sha256":sha256Bytes(bundleRaw),"bytes":int64(len(bundleRaw))};if !expectedMapEqual(dp,expectedDP){return errors.New("Signed Statement digest payload mismatch")};if !ed25519.Verify(issuer,sigStructure(p,payload),sig){return errors.New("invalid Signed Statement signature")}
	receipt:=obj(c["receipt"]);rraw,e:=b64(str(receipt["data"]));if e!=nil{return e};if !eqID(receipt["identity"],ident(rraw))||!eqID(receipt["transparencyServiceKeySpki"],ident(tsDER)){return errors.New("Receipt identity mismatch")};rp,rup,rpayload,rsig,e:=sign1(rraw);if e!=nil{return e};if rpayload!=nil{return errors.New("Receipt payload must be detached")};rpmAny,e:=decodeCBOR(rp);if e!=nil{return e};rpm:=rpmAny.(map[any]any);expectedR:=map[any]any{int64(1):int64(-8),int64(4):sha256Bytes(tsDER),int64(15):map[any]any{int64(1):"https://eigiib.example/p1-a3/transparency-service",int64(2):subject},int64(16):"application/scitt-receipt+cose",int64(395):int64(1)};if !expectedMapEqual(rpm,expectedR){return errors.New("Receipt protected header mismatch")};proofs,ok:=rup[int64(396)].(map[any]any);if !ok||len(rup)!=1{return errors.New("Receipt VDP missing")};pa,ok:=proofs[int64(-1)].([]any);if !ok||len(pa)!=1{return errors.New("Receipt inclusion proof count mismatch")};proofRaw,ok:=pa[0].([]byte);if !ok{return errors.New("Receipt proof must be bstr")};prAny,e:=decodeCBOR(proofRaw);if e!=nil{return e};pr:=prAny.([]any);if len(pr)!=3||integer(pr[0])!=1||integer(pr[1])!=0||len(arr(pr[2]))!=0{return errors.New("fixture inclusion proof mismatch")};root:=leafHash(sraw);if !ed25519.Verify(ts,sigStructure(rp,root),rsig){return errors.New("invalid Receipt signature")};if integer(binding["treeSize"])!=1||integer(binding["leafIndex"])!=0{return errors.New("declared inclusion coordinates mismatch")};reg:=obj(c["registration"]);if str(reg["location"])!="https://transparency.example/entries/"+ident(sraw).Digest||str(reg["method"])!="POST"||integer(reg["status"])!=201||str(reg["transcriptMode"])!="fixture-no-network"{return errors.New("registration transcript mismatch")};return nil
}
func sha256Bytes(b []byte)[]byte{h:=sha256.Sum256(b);return h[:]}
